version: 2.1
executors:
  go-executor:
    docker:
      - image: cimg/go:1.21
jobs:
  test:
    executor: go-executor
    steps:
      - checkout
      - run:
          name: Install linter
          command: go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
      - run:
          name: Run lint
          command: golangci-lint run

workflows:
  version: 2
  build:
    jobs:
      - test
